import React from 'react';
import { SalesChallan, User } from '../types';
import {
  FileText,
  Search,
  Plus,
  CheckCircle,
  XCircle,
  Printer,
  Calendar,
  Building2,
  AlertTriangle,
} from 'lucide-react';

interface SalesChallanViewProps {
  challans: SalesChallan[];
  currentUser: User;
  onOpenCreateModal: () => void;
  onConfirmChallan: (id: string) => Promise<void>;
  onCancelChallan: (id: string) => Promise<void>;
  onOpenPrintModal: (challan: SalesChallan) => void;
  searchTerm: string;
  setSearchTerm: (term: string) => void;
  statusFilter: string;
  setStatusFilter: (status: string) => void;
}

export const SalesChallanView: React.FC<SalesChallanViewProps> = ({
  challans,
  currentUser,
  onOpenCreateModal,
  onConfirmChallan,
  onCancelChallan,
  onOpenPrintModal,
  searchTerm,
  setSearchTerm,
  statusFilter,
  setStatusFilter,
}) => {
  const [loadingId, setLoadingId] = React.useState<string | null>(null);

  const handleConfirm = async (id: string) => {
    setLoadingId(id);
    try {
      await onConfirmChallan(id);
    } catch (err: any) {
      alert(err.message || 'Error confirming challan');
    } finally {
      setLoadingId(null);
    }
  };

  const handleCancel = async (id: string) => {
    if (!confirm('Are you sure you want to cancel this Sales Challan? Stock will be restored if confirmed.')) {
      return;
    }
    setLoadingId(id);
    try {
      await onCancelChallan(id);
    } catch (err: any) {
      alert(err.message || 'Error cancelling challan');
    } finally {
      setLoadingId(null);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-[#09090b] border border-[#27272a] p-6 rounded-2xl shadow-xl">
        <div>
          <h2 className="text-xl font-extrabold text-white flex items-center gap-2">
            <FileText className="w-6 h-6 text-indigo-400" />
            Sales Delivery Challan Module
          </h2>
          <p className="text-xs text-zinc-400 mt-1">
            Create draft or confirmed delivery challans with stock deduction logic and snapshot product archives
          </p>
        </div>

        {(currentUser.role === 'Admin' || currentUser.role === 'Sales') && (
          <button
            onClick={onOpenCreateModal}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-white text-black font-bold text-xs hover:bg-zinc-200 transition-all shadow-md"
          >
            <Plus className="w-4 h-4" />
            Generate New Challan
          </button>
        )}
      </div>

      {/* Search & Status Filters */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 bg-[#09090b] border border-[#27272a] p-4 rounded-xl">
        <div className="sm:col-span-2 relative">
          <Search className="w-4 h-4 text-zinc-500 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={searchTerm}
            onChange={e => setSearchTerm(e.target.value)}
            placeholder="Search by challan number (e.g. SCH-2026-0001), customer business..."
            className="w-full bg-[#18181b] border border-[#27272a] rounded-xl pl-10 pr-4 py-2 text-xs text-white placeholder-zinc-500 focus:outline-none focus:border-indigo-500"
          />
        </div>

        <div>
          <select
            value={statusFilter}
            onChange={e => setStatusFilter(e.target.value)}
            className="w-full bg-[#18181b] border border-[#27272a] rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-indigo-500"
          >
            <option value="ALL">All Challan Statuses</option>
            <option value="Draft">Draft Only</option>
            <option value="Confirmed">Confirmed Only</option>
            <option value="Cancelled">Cancelled Only</option>
          </select>
        </div>
      </div>

      {/* Sales Challan Table */}
      <div className="bg-[#09090b] border border-[#27272a] rounded-2xl shadow-xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs sm:text-sm">
            <thead className="bg-[#18181b] text-zinc-500 uppercase tracking-wider text-[10px] font-semibold border-b border-[#27272a]">
              <tr>
                <th className="p-4">Challan #</th>
                <th className="p-4">Customer & Business</th>
                <th className="p-4">Items Included</th>
                <th className="p-4 text-right">Total Amount</th>
                <th className="p-4">Status</th>
                <th className="p-4">Generated By</th>
                <th className="p-4 text-center">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#27272a] text-zinc-300">
              {challans.length === 0 ? (
                <tr>
                  <td colSpan={7} className="text-center p-12 text-zinc-500">
                    No sales challans found.
                  </td>
                </tr>
              ) : (
                challans.map(ch => (
                  <tr key={ch.id} className="hover:bg-zinc-900/50 transition-colors">
                    <td className="p-4 font-mono font-bold text-indigo-400 text-sm">{ch.challanNumber}</td>

                    <td className="p-4">
                      <div className="font-bold text-white text-sm flex items-center gap-1.5">
                        <Building2 className="w-3.5 h-3.5 text-indigo-400 shrink-0" />
                        {ch.customerBusiness}
                      </div>
                      <div className="text-xs text-zinc-400">{ch.customerName}</div>
                    </td>

                    <td className="p-4 text-xs text-zinc-300">
                      <div className="font-mono text-zinc-200">
                        {ch.items.length} product(s) ({ch.totalQuantity} total pcs)
                      </div>
                      <div className="text-[11px] text-zinc-500 truncate max-w-xs">
                        {ch.items.map(i => i.productName).join(', ')}
                      </div>
                    </td>

                    <td className="p-4 text-right font-mono font-bold text-emerald-400 text-sm">
                      ₹{ch.totalAmount.toLocaleString('en-IN')}
                    </td>

                    <td className="p-4">
                      <span
                        className={`px-2 py-0.5 text-[10px] font-mono font-bold rounded uppercase ${
                          ch.status === 'Confirmed'
                            ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                            : ch.status === 'Draft'
                            ? 'bg-zinc-500/20 text-zinc-400 border border-zinc-500/30'
                            : 'bg-rose-500/20 text-rose-400 border border-rose-500/30'
                        }`}
                      >
                        {ch.status}
                      </span>
                    </td>

                    <td className="p-4 text-xs text-zinc-400">
                      <div className="font-medium text-zinc-300">{ch.createdByName}</div>
                      <div className="text-[10px] font-mono">{new Date(ch.createdAt).toLocaleDateString()}</div>
                    </td>

                    <td className="p-4">
                      <div className="flex items-center justify-center gap-2">
                        {/* Print Invoice Button */}
                        <button
                          onClick={() => onOpenPrintModal(ch)}
                          className="p-2 rounded-lg bg-[#18181b] hover:bg-[#27272a] text-indigo-300 border border-[#27272a] transition-colors flex items-center gap-1 text-xs font-semibold"
                          title="Print Sales Challan / Invoice"
                        >
                          <Printer className="w-3.5 h-3.5" />
                          Print
                        </button>

                        {/* Confirm Draft Button (Only if Draft) */}
                        {ch.status === 'Draft' &&
                          (currentUser.role === 'Admin' ||
                            currentUser.role === 'Accounts' ||
                            currentUser.role === 'Warehouse' ||
                            currentUser.role === 'Sales') && (
                            <button
                              disabled={loadingId === ch.id}
                              onClick={() => handleConfirm(ch.id)}
                              className="px-2.5 py-1.5 rounded-lg bg-emerald-600/20 hover:bg-emerald-600/30 text-emerald-300 border border-emerald-500/30 text-xs font-mono font-semibold transition-colors flex items-center gap-1"
                              title="Confirm Challan and Deduct Stock"
                            >
                              <CheckCircle className="w-3.5 h-3.5" />
                              Confirm
                            </button>
                          )}

                        {/* Cancel Button */}
                        {ch.status !== 'Cancelled' &&
                          (currentUser.role === 'Admin' || currentUser.role === 'Accounts') && (
                            <button
                              disabled={loadingId === ch.id}
                              onClick={() => handleCancel(ch.id)}
                              className="p-2 rounded-lg bg-[#18181b] hover:bg-[#27272a] text-zinc-400 hover:text-rose-400 border border-[#27272a] transition-colors"
                              title="Cancel Challan"
                            >
                              <XCircle className="w-3.5 h-3.5" />
                            </button>
                          )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
